#!/bin/bash

# Creates a new scene

if [ "$1" == "" ]
then
	echo -e -n "New scene name? "
	read -e scene_name
elif [ "$1" == "-d" ]
then
	echo -e -n "WARNING-- Are you sure you want to delete scene $2? "
	read -n1 -e ans
	if [ "$ans" == "y" ]
	then
		rm -r "$2"
		echo "new_directory structure: "
		tree
		exit
	else
		echo "Canceling..."
		exit
	fi
else
	scene_name="$1"
fi

cp -r sample_scene "$scene_name"
rm "$scene_name/example_scene.tscn"

touch "$scene_name/$scene_name.tscn"
echo -e -n "[gd_scene format=1]\n\n" > "$scene_name/$scene_name.tscn"
echo -e -n "[node name=\"$scene_name\" type=\"Node2D\"]\n\n" >> "$scene_name/$scene_name.tscn"
echo "done"
echo "new directory structure: "
tree
